apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-app-deployment
  namespace: shop
  labels:
    app: ng-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-app
  template:
    metadata:
      labels:
        app: ng-app
    spec:
      containers:
      - name: ng-app
        image: 170247361816.dkr.ecr.ap-northeast-2.amazonaws.com/ng-app:latest
        ports:
        - containerPort: 4200
---        
apiVersion: v1
kind: Service
metadata:
  name: ng-app-service
  namespace: shop
  labels:
    app: ng-app
spec:
  selector:
    app: ng-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ng-app-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-0234dcaa80edc39d3,subnet-07ba2270e41ad9860
    alb.ingress.kubernetes.io/security-groups: sg-06e7915929b6a7672
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: ng-app-service
          servicePort: 80
